#!/bin/bash 
yum update -y
curl -sL https://rpm.nodesource.com/setup_10.x | sudo bash -
sudo yum install nodejs -y

yum install libcurl openssl
curl https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-amazon2-4.0.4.tgz >> /home/ec2-user/mongosetup.tgz
tar -zxvf /home/ec2-user/mongosetup.tgz
export PATH=/home/ec2-user/mongodb-linux-x86_64-amazon2-4.0.4/bin:$PATH
npm install mongodb --save
yum install git -y
git clone https://github.com/shivamXP/sampleNode.git
node /home/ec2-user/sampleNode/http_server.js


 
